### ISSUE TITLE
cleanCoords(uncert.na.pass = ) is removing NAs if TRUE and if FALSE

### ISSUE THREAD

**Issue by NACasillas** [AMBarbosa/fuzzySim#1]
I'm trying to remove the occurrences which have uncertainty of more than 10,000 meters without removing occurences where the uncertainty is NA. I have tried setting uncert.na.pass to both TRUE and to FALSE, but both return the same result.  I've attached my Occs file. 
[Occs.csv](https://github.com/user-attachments/files/17648821/Occs.csv)

Here is my code:

Console when uncert.na.pass = TRUE:
```
  > Occs <- fuzzySim::cleanCoords(Occs, coord.cols = c("decimalLongitude", "decimalLatitude"), uncert.col = "CoordinateUncertaintyInMeters", uncert.limit = 10000, uncert.na.pass = TRUE)
  645 rows in input data
  645 rows after 'rm.dup'
  645 rows after 'rm.equal'
  645 rows after 'rm.imposs'
  645 rows after 'rm.missing.any'
  645 rows after 'rm.zero.any'
  645 rows after 'rm.imprec.any'
  265 rows after 'rm.uncert' (with uncert.limit=10000 and uncert.na.pass=TRUE)
```

Console when uncert.na.pass = FALSE:
```
> Occs <- fuzzySim::cleanCoords(Occs, coord.cols = c("decimalLongitude", "decimalLatitude"), uncert.col = "CoordinateUncertaintyInMeters", uncert.limit = 10000, uncert.na.pass = FALSE)
645 rows in input data
645 rows after 'rm.dup'
645 rows after 'rm.equal'
645 rows after 'rm.imposs'
645 rows after 'rm.missing.any'
645 rows after 'rm.zero.any'
645 rows after 'rm.imprec.any'
265 rows after 'rm.uncert' (with uncert.limit=10000 and uncert.na.pass=FALSE)
```

**Comment by AMBarbosa** [comment]
What version of fuzzySim are you using? I don't get the same results with your Occs table... Try reinstalling fuzzySim to get an updated version of the package.

**Comment by NACasillas** [comment]
Oops! I wasn't updated. It's working properly now. Thanks!
